USE aissclc;

LOAD DATA INFILE 'FY97.csv'
IGNORE INTO TABLE visas97
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY98.csv'
IGNORE INTO TABLE visas98
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY99.csv'
IGNORE INTO TABLE visas99
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY00.csv'
IGNORE INTO TABLE visas00
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY01.csv'
IGNORE INTO TABLE visas01
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY02.csv'
IGNORE INTO TABLE visas02
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY03.csv'
IGNORE INTO TABLE visas03
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY04.csv'
IGNORE INTO TABLE visas04
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY05.csv'
IGNORE INTO TABLE visas05
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY06.csv'
IGNORE INTO TABLE visas06
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY07.csv'
IGNORE INTO TABLE visas07
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY08.csv'
IGNORE INTO TABLE visas08
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY09.csv'
IGNORE INTO TABLE visas09
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY10.csv'
IGNORE INTO TABLE visas10
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY11.csv'
IGNORE INTO TABLE visas11
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY12.csv'
IGNORE INTO TABLE visas12
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY13.csv'
IGNORE INTO TABLE visas13
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);

LOAD DATA INFILE 'FY14.csv'
IGNORE INTO TABLE visas14
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(CountryName, E3, E3D, E3R, F1, H1B, H1B1, J1, L1, O1, TN);